import arcpy

shapefile_path = r'C:\Users\aubrey.mccutchan\Repo\csf_prf\inputs\test_shapefiles\test_line_shapefile.shp'





if geometry_type == 'Point':
    with arcpy.da.SearchCursor(shapefile_path, ['FID','OBJL_NAME', 'SHAPE@XY']) as cursor:
        rows = list(cursor)
    for row in rows:
        id_val = row[0]
        properties_val = row[1]
        coordinates_val = list(row[2])

        geojson = {
            "geojson": {
                "id": id_val,
                "properties": {
                    "AGEN" : "AGEN",
                    "BCNSHP" : "BCNSHP",
                    "BOYSHP" : "BOYSHP",
                    "BUISHP" : "BUISHP",
                    "CALSGN" : "CALSGN",
                    "CATBUA" : "CATBUA",
                    "CATDPG" : "CATDPG",
                    "CATFOG" : "CATFOG",
                    "CATLAM" : "CATLAM",
                    "CATLIT" : "CATLIT",
                    "CATLMK" : "CATLMK",
                    "CATLND" : "CATLND",
                    "CATOBS" : "CATOBS",
                    "CATOFP" : "CATOFP",
                    "CATROS" : "CATROS",
                    "CATSIL" : "CATSIL",
                    "CATSPM" : "CATSPM",
                    "CATWAT" : "CATWAT",
                    "CATWRK" : "CATWRK",
                    "CLSDEF" : "CLSDEF",
                    "CLSNAM" : "CLSNAM",
                    "COLOUR" : "COLOUR",
                    "COLPAT" : "COLPAT",
                    "COMCHA" : "COMCHA",
                    "CONDTN" : "CONDTN",
                    "CONRAD" : "CONRAD",
                    "CONVIS" : "CONVIS",
                    "CURVEL" : "CURVEL",
                    "DATEND" : "DATEND",
                    "DATSTA" : "DATSTA",
                    "ELEVAT" : "ELEVAT",
                    "ESTRNG" : "ESTRNG",
                    "EXCLIT" : "EXCLIT",
                    "EXPSOU" : "EXPSOU",
                    "FFPT_RIND" : "FFPT_RIND",
                    "FIDN" : "FIDN",
                    "FIDS" : "FIDS",
                    "FUNCTN" : "FUNCTN",
                    "GRUP" : "GRUP",
                    "HEIGHT" : "HEIGHT",
                    "INFORM" : "INFORM",
                    "LITCHR" : "LITCHR",
                    "LITVIS" : "LITVIS",
                    "LNAM" : "LNAM",
                    "LNAM_REFS" : "LNAM_REFS",
                    "MARSYS" : "MARSYS",
                    "MLTYLT" : "MLTYLT",
                    "NATCON" : "NATCON",
                    "NATION" : "NATION",
                    "NATQUA" : "NATQUA",
                    "NATSUR" : "NATSUR",
                    "NINFOM" : "NINFOM",
                    "NOBJNM" : "NOBJNM",
                    "NTXTDS" : "NTXTDS",
                    "OBJL" : "OBJL",
                    "OBJNAM" : "OBJNAM",
                    "ORIENT" : "ORIENT",
                    "PEREND" : "PEREND",
                    "PERSTA" : "PERSTA",
                    "PICREP" : "PICREP",
                    "PRIM" : "PRIM",
                    "PRODCT" : "PRODCT",
                    "QUASOU" : "QUASOU",
                    "RCID" : "RCID",
                    "RECDAT" : "RECDAT",
                    "RECIND" : "RECIND",
                    "RESTRN" : "RESTRN",
                    "RVER" : "RVER",
                    "RYRMGV" : "RYRMGV",
                    "SCALE_LVL" : "SCALE_LVL",
                    "SCAMAX" : "SCAMAX",
                    "SCAMIN" : "SCAMIN",
                    "SECTR1" : "SECTR1",
                    "SECTR2" : "SECTR2",
                    "SIGFRQ" : "SIGFRQ",
                    "SIGGEN" : "SIGGEN",
                    "SIGGRP" : "SIGGRP",
                    "SIGPER" : "SIGPER",
                    "SIGSEQ" : "SIGSEQ",
                    "SORDAT" : "SORDAT",
                    "SORIND" : "SORIND",
                    "SOUACC" : "SOUACC",
                    "STATUS" : "STATUS",
                    "SYMINS" : "SYMINS",
                    "TECSOU" : "TECSOU",
                    "TOPSHP" : "TOPSHP",
                    "TXTDSC" : "TXTDSC",
                    "VALACM" : "VALACM",
                    "VALMAG" : "VALMAG",
                    "VALMXR" : "VALMXR",
                    "VALNMR" : "VALNMR",
                    "VALSOU" : "VALSOU",
                    "VERACC" : "VERACC",
                    "VERDAT" : "VERDAT",
                    "VERLEN" : "VERLEN",
                    "WATLEV" : "WATLEV",
                    "OBJL_NAME" : properties_val,
                    "asgnmt" : "asgnmt",
                    "invreq" : "invreq",
                    "OBJECTID_1" : "OBJECTID_1",
                    "Join_Count" : "Join_Count",
                    "TARGET_FID" : "TARGET_FID",
                    "POSACC" : "POSACC",
                    "QUAPOS" : "QUAPOS",
                    "RCID_1" : "RCID_1",
                    "RCNM" : "RCNM",
                    "RUIN" : "RUIN",
                    "RVER_1" : "RVER_1",
                    "SCALE_LVL_" : "SCALE_LVL_"},
                "geometry": {
                    "type": geometry_type,
                    "coordinates": coordinates_val,
                }
            }
        }

        geojson_outputs.append(geojson)
elif geometry_type == 'LineString':
    for row in arcpy.da.SearchCursor(shapefile_path, ['FID','OBJL_NAME', 'SHAPE@']):
        id_val = row[0]
        properties_val = row[1]

        coordinates_val = []
        for part in row[2]:
            for pnt in part:
                coordinates_val.append([pnt.X, pnt.Y])

        geojson = {
            "geojson": {
                "id": id_val,
                "properties": {
                    "AGEN" : "AGEN",
                    "BCNSHP" : "BCNSHP",
                    "BOYSHP" : "BOYSHP",
                    "BUISHP" : "BUISHP",
                    "CALSGN" : "CALSGN",
                    "CATBUA" : "CATBUA",
                    "CATDPG" : "CATDPG",
                    "CATFOG" : "CATFOG",
                    "CATLAM" : "CATLAM",
                    "CATLIT" : "CATLIT",
                    "CATLMK" : "CATLMK",
                    "CATLND" : "CATLND",
                    "CATOBS" : "CATOBS",
                    "CATOFP" : "CATOFP",
                    "CATROS" : "CATROS",
                    "CATSIL" : "CATSIL",
                    "CATSPM" : "CATSPM",
                    "CATWAT" : "CATWAT",
                    "CATWRK" : "CATWRK",
                    "CLSDEF" : "CLSDEF",
                    "CLSNAM" : "CLSNAM",
                    "COLOUR" : "COLOUR",
                    "COLPAT" : "COLPAT",
                    "COMCHA" : "COMCHA",
                    "CONDTN" : "CONDTN",
                    "CONRAD" : "CONRAD",
                    "CONVIS" : "CONVIS",
                    "CURVEL" : "CURVEL",
                    "DATEND" : "DATEND",
                    "DATSTA" : "DATSTA",
                    "ELEVAT" : "ELEVAT",
                    "ESTRNG" : "ESTRNG",
                    "EXCLIT" : "EXCLIT",
                    "EXPSOU" : "EXPSOU",
                    "FFPT_RIND" : "FFPT_RIND",
                    "FIDN" : "FIDN",
                    "FIDS" : "FIDS",
                    "FUNCTN" : "FUNCTN",
                    "GRUP" : "GRUP",
                    "HEIGHT" : "HEIGHT",
                    "INFORM" : "INFORM",
                    "LITCHR" : "LITCHR",
                    "LITVIS" : "LITVIS",
                    "LNAM" : "LNAM",
                    "LNAM_REFS" : "LNAM_REFS",
                    "MARSYS" : "MARSYS",
                    "MLTYLT" : "MLTYLT",
                    "NATCON" : "NATCON",
                    "NATION" : "NATION",
                    "NATQUA" : "NATQUA",
                    "NATSUR" : "NATSUR",
                    "NINFOM" : "NINFOM",
                    "NOBJNM" : "NOBJNM",
                    "NTXTDS" : "NTXTDS",
                    "OBJL" : "OBJL",
                    "OBJNAM" : "OBJNAM",
                    "ORIENT" : "ORIENT",
                    "PEREND" : "PEREND",
                    "PERSTA" : "PERSTA",
                    "PICREP" : "PICREP",
                    "PRIM" : "PRIM",
                    "PRODCT" : "PRODCT",
                    "QUASOU" : "QUASOU",
                    "RCID" : "RCID",
                    "RECDAT" : "RECDAT",
                    "RECIND" : "RECIND",
                    "RESTRN" : "RESTRN",
                    "RVER" : "RVER",
                    "RYRMGV" : "RYRMGV",
                    "SCALE_LVL" : "SCALE_LVL",
                    "SCAMAX" : "SCAMAX",
                    "SCAMIN" : "SCAMIN",
                    "SECTR1" : "SECTR1",
                    "SECTR2" : "SECTR2",
                    "SIGFRQ" : "SIGFRQ",
                    "SIGGEN" : "SIGGEN",
                    "SIGGRP" : "SIGGRP",
                    "SIGPER" : "SIGPER",
                    "SIGSEQ" : "SIGSEQ",
                    "SORDAT" : "SORDAT",
                    "SORIND" : "SORIND",
                    "SOUACC" : "SOUACC",
                    "STATUS" : "STATUS",
                    "SYMINS" : "SYMINS",
                    "TECSOU" : "TECSOU",
                    "TOPSHP" : "TOPSHP",
                    "TXTDSC" : "TXTDSC",
                    "VALACM" : "VALACM",
                    "VALMAG" : "VALMAG",
                    "VALMXR" : "VALMXR",
                    "VALNMR" : "VALNMR",
                    "VALSOU" : "VALSOU",
                    "VERACC" : "VERACC",
                    "VERDAT" : "VERDAT",
                    "VERLEN" : "VERLEN",
                    "WATLEV" : "WATLEV",
                    "OBJL_NAME" : properties_val,
                    "asgnmt" : "asgnmt",
                    "invreq" : "invreq",
                    "OBJECTID_1" : "OBJECTID_1",
                    "Join_Count" : "Join_Count",
                    "TARGET_FID" : "TARGET_FID",
                    "POSACC" : "POSACC",
                    "QUAPOS" : "QUAPOS",
                    "RCID_1" : "RCID_1",
                    "RCNM" : "RCNM",
                    "RUIN" : "RUIN",
                    "RVER_1" : "RVER_1",
                    "SCALE_LVL_" : "SCALE_LVL_"},
                "geometry": coordinates_val
            }
        }
        geojson_outputs.append(geojson)
    
elif geometry_type == 'Polygon':
    for row in arcpy.da.SearchCursor(shapefile_path, ['FID','OBJL_NAME', 'SHAPE@']):
        id_val = row[0]
        properties_val = row[1]

        coordinates_val = []
        for part in row[2]:
            for pnt in part:
                coordinates_val.append([pnt.X, pnt.Y])

        geojson = {
            "geojson": {
                "id": id_val,
                "properties": {
                    "AGEN" : "AGEN",
                    "BCNSHP" : "BCNSHP",
                    "BOYSHP" : "BOYSHP",
                    "BUISHP" : "BUISHP",
                    "CALSGN" : "CALSGN",
                    "CATBUA" : "CATBUA",
                    "CATDPG" : "CATDPG",
                    "CATFOG" : "CATFOG",
                    "CATLAM" : "CATLAM",
                    "CATLIT" : "CATLIT",
                    "CATLMK" : "CATLMK",
                    "CATLND" : "CATLND",
                    "CATOBS" : "CATOBS",
                    "CATOFP" : "CATOFP",
                    "CATROS" : "CATROS",
                    "CATSIL" : "CATSIL",
                    "CATSPM" : "CATSPM",
                    "CATWAT" : "CATWAT",
                    "CATWRK" : "CATWRK",
                    "CLSDEF" : "CLSDEF",
                    "CLSNAM" : "CLSNAM",
                    "COLOUR" : "COLOUR",
                    "COLPAT" : "COLPAT",
                    "COMCHA" : "COMCHA",
                    "CONDTN" : "CONDTN",
                    "CONRAD" : "CONRAD",
                    "CONVIS" : "CONVIS",
                    "CURVEL" : "CURVEL",
                    "DATEND" : "DATEND",
                    "DATSTA" : "DATSTA",
                    "ELEVAT" : "ELEVAT",
                    "ESTRNG" : "ESTRNG",
                    "EXCLIT" : "EXCLIT",
                    "EXPSOU" : "EXPSOU",
                    "FFPT_RIND" : "FFPT_RIND",
                    "FIDN" : "FIDN",
                    "FIDS" : "FIDS",
                    "FUNCTN" : "FUNCTN",
                    "GRUP" : "GRUP",
                    "HEIGHT" : "HEIGHT",
                    "INFORM" : "INFORM",
                    "LITCHR" : "LITCHR",
                    "LITVIS" : "LITVIS",
                    "LNAM" : "LNAM",
                    "LNAM_REFS" : "LNAM_REFS",
                    "MARSYS" : "MARSYS",
                    "MLTYLT" : "MLTYLT",
                    "NATCON" : "NATCON",
                    "NATION" : "NATION",
                    "NATQUA" : "NATQUA",
                    "NATSUR" : "NATSUR",
                    "NINFOM" : "NINFOM",
                    "NOBJNM" : "NOBJNM",
                    "NTXTDS" : "NTXTDS",
                    "OBJL" : "OBJL",
                    "OBJNAM" : "OBJNAM",
                    "ORIENT" : "ORIENT",
                    "PEREND" : "PEREND",
                    "PERSTA" : "PERSTA",
                    "PICREP" : "PICREP",
                    "PRIM" : "PRIM",
                    "PRODCT" : "PRODCT",
                    "QUASOU" : "QUASOU",
                    "RCID" : "RCID",
                    "RECDAT" : "RECDAT",
                    "RECIND" : "RECIND",
                    "RESTRN" : "RESTRN",
                    "RVER" : "RVER",
                    "RYRMGV" : "RYRMGV",
                    "SCALE_LVL" : "SCALE_LVL",
                    "SCAMAX" : "SCAMAX",
                    "SCAMIN" : "SCAMIN",
                    "SECTR1" : "SECTR1",
                    "SECTR2" : "SECTR2",
                    "SIGFRQ" : "SIGFRQ",
                    "SIGGEN" : "SIGGEN",
                    "SIGGRP" : "SIGGRP",
                    "SIGPER" : "SIGPER",
                    "SIGSEQ" : "SIGSEQ",
                    "SORDAT" : "SORDAT",
                    "SORIND" : "SORIND",
                    "SOUACC" : "SOUACC",
                    "STATUS" : "STATUS",
                    "SYMINS" : "SYMINS",
                    "TECSOU" : "TECSOU",
                    "TOPSHP" : "TOPSHP",
                    "TXTDSC" : "TXTDSC",
                    "VALACM" : "VALACM",
                    "VALMAG" : "VALMAG",
                    "VALMXR" : "VALMXR",
                    "VALNMR" : "VALNMR",
                    "VALSOU" : "VALSOU",
                    "VERACC" : "VERACC",
                    "VERDAT" : "VERDAT",
                    "VERLEN" : "VERLEN",
                    "WATLEV" : "WATLEV",
                    "OBJL_NAME" : properties_val,
                    "asgnmt" : "asgnmt",
                    "invreq" : "invreq",
                    "OBJECTID_1" : "OBJECTID_1",
                    "Join_Count" : "Join_Count",
                    "TARGET_FID" : "TARGET_FID",
                    "POSACC" : "POSACC",
                    "QUAPOS" : "QUAPOS",
                    "RCID_1" : "RCID_1",
                    "RCNM" : "RCNM",
                    "RUIN" : "RUIN",
                    "RVER_1" : "RVER_1",
                    "SCALE_LVL_" : "SCALE_LVL_"},
                "geometry": {
                    "type": geometry_type,
                    "coordinates": [coordinates_val],
                }
            }
        }
        geojson_outputs.append(geojson)


print(geojson_outputs)
