class_codes = {
    1: ("ADMARE", "Administration area (Named)"),
    2: ("AIRARE", "Airport / airfield"),
    3: ("ACHBRT", "Anchor berth"),
    4: ("ACHARE", "Anchorage area"),
    5: ("BCNCAR", "Beacon, cardinal"),
    6: ("BCNISD", "Beacon, isolated danger"),
    7: ("BCNLAT", "Beacon, lateral"),
    8: ("BCNSAW", "Beacon, safe water"),
    9: ("BCNSPP", "Beacon, special purpose/general"),
    10: ("BERTHS", "Berth"),
    11: ("BRIDGE", "Bridge"),
    12: ("BUISGL", "Building, single"),
    13: ("BUAARE", "Built-up area"),
    14: ("BOYCAR", "Buoy, cardinal"),
    15: ("BOYINB", "Buoy, installation"),
    16: ("BOYISD", "Buoy, isolated danger"),
    17: ("BOYLAT", "Buoy, lateral"),
    18: ("BOYSAW", "Buoy, safe water"),
    19: ("BOYSPP", "Buoy, special purpose/general"),
    20: ("CBLARE", "Cable area"),
    21: ("CBLOHD", "Cable, overhead"),
    22: ("CBLSUB", "Cable, submarine"),
    23: ("CANALS", "Canal"),
    24: ("CANBNK", "Canal bank"),
    25: ("CTSARE", "Cargo transshipment area"),
    26: ("CAUSWY", "Causeway"),
    27: ("CTNARE", "Caution area"),
    28: ("CHKPNT", "Checkpoint"),
    29: ("CGUSTA", "Coastguard station"),
    30: ("COALNE", "Coastline"),
    31: ("CONZNE", "Contiguous zone"),
    32: ("COSARE", "Continental shelf area"),
    33: ("CTRPNT", "Control point"),
    34: ("CONVYR", "Conveyor"),
    35: ("CRANES", "Crane"),
    36: ("CURENT", "Current - non - gravitational"),
    37: ("CUSZNE", "Custom zone"),
    38: ("DAMCON", "Dam"),
    39: ("DAYMAR", "Daymark"),
    40: ("DWRTCL", "Deep water route centerline"),
    41: ("DWRTPT", "Deep water route part"),
    42: ("DEPARE", "Depth area"),
    43: ("DEPCNT", "Depth contour"),
    44: ("DISMAR", "Distance mark"),
    45: ("DOCARE", "Dock area"),
    46: ("DRGARE", "Dredged area"),
    47: ("DRYDOC", "Dry dock"),
    48: ("DMPGRD", "Dumping ground"),
    49: ("DYKCON", "Dyke"),
    50: ("EXEZNE", "Exclusive Economic Zone"),
    51: ("FAIRWY", "Fairway"),
    52: ("FNCLNE", "Fence/wall"),
    53: ("FERYRT", "Ferry route"),
    54: ("FSHZNE", "Fishery zone"),
    55: ("FSHFAC", "Fishing facility"),
    56: ("FSHGRD", "Fishing ground"),
    57: ("FLODOC", "Floating dock"),
    58: ("FOGSIG", "Fog signal"),
    59: ("FORSTC", "Fortified structure"),
    60: ("FRPARE", "Free port area"),
    61: ("GATCON", "Gate"),
    62: ("GRIDRN", "Gridiron"),
    63: ("HRBARE", "Harbour area (administrative)"),
    64: ("HRBFAC", "Harbour facility"),
    65: ("HULKES", "Hulk"),
    66: ("ICEARE", "Ice area"),
    67: ("ICNARE", "Incineration area"),
    68: ("ISTZNE", "Inshore traffic zone"),
    69: ("LAKARE", "Lake"),
    70: ("LAKSHR", "Lake shore"),
    71: ("LNDARE", "Land area"),
    72: ("LNDELV", "Land elevation"),
    73: ("LNDRGN", "Land region"),
    74: ("LNDMRK", "Landmark"),
    75: ("LIGHTS", "Light"),
    76: ("LITFLT", "Light float"),
    77: ("LITVES", "Light vessel"),
    78: ("LOCMAG", "Local magnetic anomaly"),
    79: ("LOKBSN", "Lock basin"),
    80: ("LOGPON", "Log pond"),
    81: ("MAGVAR", "Magnetic variation"),
    82: ("MARCUL", "Marine farm/culture"),
    83: ("MIPARE", "Military practice area"),
    84: ("MORFAC", "Mooring/warping facility"),
    85: ("NAVLNE", "Navigation line"),
    86: ("OBSTRN", "Obstruction"),
    87: ("OFSPLF", "Offshore platform"),
    88: ("OSPARE", "Offshore production area"),
    89: ("OILBAR", "Oil barrier"),
    90: ("PILPNT", "Pile"),
    91: ("PILBOP", "Pilot boarding place"),
    92: ("PIPARE", "Pipeline area"),
    93: ("PIPOHD", "Pipeline, overhead"),
    94: ("PIPSOL", "Pipeline, submarine/on land"),
    95: ("PONTON", "Pontoon"),
    96: ("PRCARE", "Precautionary area"),
    97: ("PRDARE", "Production / storage area"),
    98: ("PYLONS", "Pylon/bridge support"),
    99: ("RADLNE", "Radar line"),
    100: ("RADRNG", "Radar range"),
    101: ("RADRFL", "Radar reflector"),
    102: ("RADSTA", "Radar station"),
    103: ("RTPBCN", "Radar transponder beacon"),
    104: ("RDOCAL", "Radio calling-in point"),
    105: ("RDOSTA", "Radio station"),
    106: ("RAILWY", "Railway"),
    107: ("RAPIDS", "Rapids"),
    108: ("RCRTCL", "Recommended route centerline"),
    109: ("RECTRC", "Recommended track"),
    110: ("RCTLPT", "Recommended Traffic Lane Part"),
    111: ("RSCSTA", "Rescue station"),
    112: ("RESARE", "Restricted area"),
    113: ("RETRFL", "Retro-reflector"),
    114: ("RIVERS", "River"),
    115: ("RIVBNK", "River bank"),
    116: ("ROADWY", "Road"),
    117: ("RUNWAY", "Runway"),
    118: ("SNDWAV", "Sand waves"),
    119: ("SEAARE", "Sea area / named water area"),
    120: ("SPLARE", "Sea-plane landing area"),
    121: ("SBDARE", "Seabed area"),
    122: ("SLCONS", "Shoreline Construction"),
    123: ("SISTAT", "Signal station, traffic"),
    124: ("SISTAW", "Signal station, warning"),
    125: ("SILTNK", "Silo / tank"),
    126: ("SLOTOP", "Slope topline"),
    127: ("SLOGRD", "Sloping ground"),
    128: ("SMCFAC", "Small craft facility"),
    129: ("SOUNDG", "Sounding"),
    130: ("SPRING", "Spring"),
    131: ("SQUARE", "Square"),
    132: ("STSLNE", "Straight territorial sea baseline"),
    133: ("SUBTLN", "Submarine transit lane"),
    134: ("SWPARE", "Swept Area"),
    135: ("TESARE", "Territorial sea area"),
    136: ("TS_PRH", "Tidal stream - harmonic prediction"),
    137: ("TS_PNH", "Tidal stream - non-harmonic prediction"),
    138: ("TS_PAD", "Tidal stream panel data"),
    139: ("TS_TIS", "Tidal stream - time series"),
    140: ("T_HMON", "Tide - harmonic prediction"),
    141: ("T_NHMN", "Tide - non-harmonic prediction"),
    142: ("T_TIMS", "Tidal stream - time series"),
    143: ("TIDEWY", "Tideway"),
    144: ("TOPMAR", "Top mark"),
    145: ("TSELNE", "Traffic Separation Line"),
    146: ("TSSBND", "Traffic Separation Scheme  Boundary"),
    147: ("TSSCRS", "Traffic Separation Scheme Crossing"),
    148: ("TSSLPT", "Traffic Separation Scheme  Lane part"),
    149: ("TSSRON", "Traffic Separation Scheme  Roundabout"),
    150: ("TSEZNE", "Traffic Separation Zone"),
    151: ("TUNNEL", "Tunnel"),
    152: ("TWRTPT", "Two-way route  part"),
    153: ("UWTROC", "Underwater rock / awash rock"),
    154: ("UNSARE", "Unsurveyed area"),
    155: ("VEGATN", "Vegetation"),
    156: ("WATTUR", "Water turbulence"),
    157: ("WATFAL", "Waterfall"),
    158: ("WEDKLP", "Weed/Kelp"),
    159: ("WRECKS", "Wreck"),
    160: ("TS_FEB", "Tidal stream - flood/ebb"),
    161: ("ARCSLN", "Archipelagic Sea Lane"),
    162: ("ASLXIS", "Archipelagic Sea Lane Axis"),
    163: ("NEWOBJ", "New Object"),
    300: ("M_ACCY", "Accuracy of data"),
    301: ("M_CSCL", "Compilation scale of data"),
    302: ("M_COVR", "Coverage"),
    303: ("M_HDAT", "Horizontal datum of data"),
    304: ("M_HOPA", "Horizontal datum shift parameters"),
    305: ("M_NPUB", "Nautical publication information"),
    306: ("M_NSYS", "Navigational system of marks"),
    307: ("M_PROD", "Production information"),
    308: ("M_QUAL", "Quality of data"),
    309: ("M_SDAT", "Sounding datum"),
    310: ("M_SREL", "Survey reliability"),
    311: ("M_UNIT", "Units of measurement of data"),
    312: ("M_VDAT", "Vertical datum of data"),
    313: ("m_pyup", "Pydro update data"),
    400: ("C_AGGR", "Aggregation"),
    401: ("C_ASSO", "Association"),
    402: ("C_STAC", "Stacked on/stacked under"),
    500: ("$AREAS", "Cartographic area"),
    501: ("$LINES", "Cartographic line"),
    502: ("$CSYMB", "Cartographic symbol"),
    503: ("$COMPS", "Compass"),
    504: ("$TEXTS", "Text"),
    644: ("cvrage", "Coverage Area"),
    696: ("brklne", "Breakline"),
    11001: ("usrmrk", "User marker"),
    11003: ("survey", "Survey project"),
    11004: ("surfac", "Bathymetric surface"),
    11008: ("prodpf", "Product Profile"),
    'OTHER': ("", "")
}